workspace:
  base: /go

pipeline:
  test:
    image: golang:1.7.5
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test
      - go build -ldflags "-s -w -X main.version=$DRONE_BUILD_NUMBER"
    when:
      event: push

  publish:
    # coverage:
    #   when:
    #     branch: master
    master:
      image: plugins/docker
      username: ${DOCKER_USER}
      password: ${DOCKER_PASS}
      email: ${DOCKER_EMAIL}
      repo: stayfari/drone-gcr
      tag: latest
      when:
        branch: master
    develop:
      image: plugins/docker
      username: ${DOCKER_USER}
      password: ${DOCKER_PASS}
      email: ${DOCKER_EMAIL}
      repo: stayfari/drone-gcr
      tag: develop
      when:
        branch: develop

plugin:
  name: Google Container Registry
  desc: Build and publish images to Google Container Registry
  type: publish
  image: stayfari/drone-gcr
  labels:
    - docker
    - image
    - container
    - google
