pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    image: plugins/docker
    repo: plugins/drone-gcr
    tag: [ "latest" ]
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    when:
      branch: release/0.4
      event: push

plugin:
  name: Google Container Registry
  desc: Build and publish images to Google Container Registry
  type: publish
  image: plugins/drone-gcr
  labels:
    - docker
    - image
    - container
    - google
